### ISSUE TITLE
Reinstall System Issue

### ISSUE THREAD

**Issue by OneNineThree** [RohitVerma882/Heimdoo#2]
Hello bro, I'm writing this because i don't know how to use your app for reinstall the original rom for my phone **(SM-A105M)**. I leaved it on the bootloader screen because I've never did something like this. I'm a technology fanatic so i hope you will respond. I was trying to install TWRP but it didn't work. Idk why.

**Comment by RohitVerma882** [comment]
Share error screenshot

**Comment by RohitVerma882** [comment]
Also heimdall does not work for all devices, specially new devices
